---
version: '3.6'
services:
  database:
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
    image: mysql:${MYSQL_VERSION:?err}

  sut:
    build:
      context: .
      args:
        WORDPRESS_VERSION: ${WORDPRESS_VERSION:?err}
        PHP_VERSION: ${PHP_VERSION:?err}
    command:
      - sh
      - -c
      - "phpunit --version && phpcs --version"
    depends_on:
      - database
    environment:
      DATABASE_PASSWORD: examplepass
