name: ci

on:
  push:
    branches:
      # Only on main branch
      - 'main'
      # Also "automate" branch. @todo Remove this.
      - 'automate'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.4 ]
        wp-version: [ 5.9 ]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: josh412/wp-phpunit:latest
          #https://andrei-calazans.com/posts/2021-06-23/passing-secrets-github-actions-docker
          secrets: |
            "WORDPRESS_VERSION=${{ matrix.wp-version }}"
            "PHP_IMAGE_TAG=${{ matrix.php-version }}"
